In [4]:
import numpy as np

In [1]:
char_01 = "Learning Python is fun",
char_02 = "Learning Numpy is fun",

In [5]:
np.char.add(char_01, char_02)

array(['Learning Python is funLearning Numpy is fun'], dtype='<U43')

In [6]:
np.char.lower(char_01)

array(['learning python is fun'], dtype='<U22')

In [7]:
np.char.upper(char_02)

array(['LEARNING NUMPY IS FUN'], dtype='<U21')

In [8]:
np.char.title(char_01)

array(['Learning Python Is Fun'], dtype='<U22')

In [9]:
np.char.center(char_02, 50, fillchar='*')

array(['**************Learning Numpy is fun***************'], dtype='<U50')

In [10]:
np.char.split(char_01)

array([list(['Learning', 'Python', 'is', 'fun'])], dtype=object)

In [11]:
np.char.splitlines('a\nb\nc')

array(list(['a', 'b', 'c']), dtype=object)

In [15]:
np.char.join([":","/"],[char_01,char_02])

array([['L:e:a:r:n:i:n:g: :P:y:t:h:o:n: :i:s: :f:u:n',
        'L/e/a/r/n/i/n/g/ /P/y/t/h/o/n/ /i/s/ /f/u/n'],
       ['L:e:a:r:n:i:n:g: :N:u:m:p:y: :i:s: :f:u:n',
        'L/e/a/r/n/i/n/g/ /N/u/m/p/y/ /i/s/ /f/u/n']], dtype='<U43')

In [13]:
np.char.replace(char_01,"fun","amazing!")

array(['Learning Python is amazing!'], dtype='<U27')

In [16]:
np.char.equal(char_01,char_02)

array([False])

In [18]:
np.char.count(char_01,"f")

array([1])

In [23]:
np.char.find(char_01,"Python")

array([-1])