In [1]:
# Import numpy as np

In [2]:
import numpy as np

In [3]:
# Create an one dimension array and store it in a variable called arr_1d, then print it

In [4]:
arr_1d = np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [5]:
# Check the type of the variable called arr_1d

In [6]:
type(arr_1d)

numpy.ndarray

In [7]:
# Check the dimension of the array

In [8]:
arr_1d.ndim

1

In [9]:
# Create an two dimension array and store it in a variable called arr_2d, then print it

In [10]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
# Check the type of the variable called arr_2d

In [12]:
type(arr_2d)

numpy.ndarray

In [13]:
# Check the dimension of the array

In [14]:
arr_2d.ndim

2

In [15]:
# Check the size of the array

In [16]:
arr_2d.size

8

In [17]:
# Check the shape of the array

In [18]:
arr_2d.shape

(2, 4)

In [19]:
# Tuples (2rows, 4colomns)

In [20]:
# Check the data type of the array

In [21]:
arr_2d.dtype

dtype('int32')

In [22]:
asd = arr_1d + arr_2d