In [2]:
# Imports the numpy and random modules
import numpy as np
import random 

In [3]:
# Returns a 1-D array containing a single random float between 0 and 1
np.random.random(1)

array([0.48607266])

In [7]:
# Generates a 3x3 array with random floats between 0 and 1
np.random.random((3,3))   


array([[0.12545938, 0.86662644, 0.4811359 ],
       [0.42914884, 0.35041779, 0.01089962],
       [0.96037636, 0.79891321, 0.53776777]])

In [8]:
# Returns a random integer between 1 and 100
np.random.randint(1,100)

57

In [9]:
# Generates a 10x10 array with random integers between 1 and 100
np.random.randint(1,100,(10,10))

array([[ 1, 86, 13, 82, 85,  6, 57, 48, 17, 77],
       [53, 17, 20, 11, 70, 93, 67,  3, 94, 79],
       [54, 10, 92, 58, 14, 38, 65, 82,  7, 93],
       [32, 38, 12, 97, 40,  6,  5, 26, 46, 81],
       [64, 56, 50, 88, 63, 26, 25,  4, 23, 12],
       [77, 13, 58, 89, 49, 11, 90, 46, 91, 24],
       [68, 59, 60, 42, 44, 30, 40, 80, 74, 26],
       [ 3, 23, 72,  1, 88, 89, 38, 34, 23, 29],
       [76, 28,  2, 16, 70, 30, 60, 94, 30, 25],
       [53, 68, 21, 78, 23, 30, 43, 31, 85, 28]])

In [12]:
# Generates a 3D array with shape (2, 3, 3) containing
# random integers between 1 and 7 inclusive
np.random.randint(1,8,(2,3,3))

array([[[3, 5, 1],
        [1, 5, 7],
        [5, 6, 4]],

       [[3, 2, 2],
        [6, 3, 4],
        [3, 4, 1]]])

In [13]:
# Sets the random seed to 10
# Generates a 10x10 array of random integers between 1 and 5
np.random.seed(10)
np.random.randint(1,5,(10,10))

array([[2, 2, 1, 4, 1, 2, 4, 1, 2, 2],
       [1, 2, 2, 3, 1, 2, 1, 3, 1, 3],
       [1, 4, 1, 1, 4, 4, 3, 1, 4, 3],
       [3, 2, 1, 1, 3, 2, 4, 3, 2, 2],
       [2, 4, 2, 3, 2, 1, 3, 3, 3, 2],
       [1, 2, 4, 2, 1, 4, 3, 2, 2, 3],
       [4, 3, 1, 4, 1, 3, 1, 2, 4, 3],
       [1, 3, 4, 1, 4, 2, 3, 4, 4, 1],
       [2, 1, 3, 1, 1, 1, 2, 1, 4, 1],
       [1, 3, 1, 3, 3, 1, 4, 2, 1, 4]])

In [16]:
# Generate a 1-dimensional array containing 
# random values between 0 and 1
np.random.rand(1)

array([0.43401399])

In [19]:
# Generates a 2 x 2 array with random values between 0 and 1
np.random.rand(2,2)

array([[0.65039718, 0.60103895],
       [0.8052232 , 0.52164715]])

In [20]:
# Generate a 3x3 array containing random values sampled from a standard normal distribution
np.random.randn(3,3)

array([[-0.27124799,  0.61320418, -0.26731719],
       [-0.54930901,  0.1327083 , -0.47614201],
       [ 1.30847308,  0.19501328,  0.40020999]])

In [24]:
# Selects a random sample from the given list.
list = [1,2,3,4,5]
np.random.choice(list)

1

In [27]:
# Generate 11 random samples from the list variable using np.random.choice
for i in range(11):
    print(np.random.choice(list))

1
3
5
3
1
1
3
4
1
5
5


In [28]:
"""
Randomly permute a sequence / generate a random permutation of a list.

Parameters
----------
list : array_like
    Input array to permute.

Returns
-------
permuted_list : ndarray
    Permuted array.
"""
np.random.permutation(list)

array([5, 2, 4, 3, 1])