In [28]:
import numpy as np

In [31]:
# What is arange function in numpy?
# A: Certainly! The numpy.arange() function creates arrays with evenly spaced values within a specified interval. It allows you to define the start, stop, and step size for generating the array. 
# For example:

# Generate an array from 0 to 9 (exclusive) with a step of 2
my_array = np.arange(start=0, stop=10, step=2)
print(my_array)


[0 2 4 6 8]


In [33]:
# What is linespace function in numpy?
# A:  The numpy.linspace() function in NumPy creates an array of evenly spaced numbers within a specified interval. It allows you to define the start and end points of the sequence, along with the number of evenly spaced samples you want to generate between them. For Example:

my_array = np.linspace(start=2.0, stop=3.0, num=5)
print(my_array)


[2.   2.25 2.5  2.75 3.  ]


In [35]:
# What is reshape function in numpy?
# A: The numpy.reshape() function in NumPy allows you to give a new shape to an array without changing its data.
# For Example.

a = np.arange(6).reshape((3, 2))
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [37]:
# What is ravel function in numpy?
# A: The numpy.ravel() function in NumPy returns a contiguous flattened array. It transforms a multi-dimensional array into a 1-D array by concatenating its elements along a single axis.
# For Example:

x = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = np.ravel(x)
print(flattened_array)  


[1 2 3 4 5 6]


In [38]:
# What is flatten funtion in numpy?
# A: The numpy.ndarray.flatten() function in NumPy returns a copy of an array collapsed into one dimension. It transforms a multi-dimensional array into a 1-D array by concatenating its elements along a single axis. You can specify the order of flattening, such as row-major (‘C’) or column-major (‘F’) order12. 
# For example:

# Create a 2D array
a = np.array([[1, 2], [3, 4]])

# Flatten the array (default: row-major order)
flattened_array = a.flatten()
print(flattened_array) 

# Flatten with column-major order
flattened_column_major = a.flatten(order='F')
print(flattened_column_major) 

[1 2 3 4]
[1 3 2 4]


In [39]:
# What is transpose funtion in numpy?
# A: The numpy.transpose() function in NumPy reverses or permutes the axes of an ndarray.

import numpy as np

a = np.array([[1, 2], [3, 4]])
transposed_array = np.transpose(a)
print(transposed_array)

[[1 3]
 [2 4]]
